ProjektKatthem/Controllers/AdoptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using ProjektKatthem.Data;
using ProjektKatthem.Models;

namespace ProjektKatthem.Controllers
{
	[Authorize]
	public class AdoptsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdoptsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Adopts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Adopt.Include(a => a.Cats);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Adopts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Adopt == null)
            {
                return NotFound();
            }

            var adopt = await _context.Adopt
                .Include(a => a.Cats)
                .FirstOrDefaultAsync(m => m.AdoptId == id);
            if (adopt == null)
            {
                return NotFound();
            }

            return View(adopt);
        }

        // GET: Adopts/Create
        public IActionResult Create()
        {
            var catContext = _context.Cats
                .Where(c => c.Adopted == false)
                .Select(c => c)
                .ToList();

            ViewData["CatsId"] = new SelectList(catContext, "Id", "Name");
            
            return View();
        }

        // POST: Adopts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdoptId,AdoptName,Email,Number,Pickup,CatsId")] Adopt adopt)
        {
            if (ModelState.IsValid)
            {
                //ändrar då adoption bokar katten
                var adoptCat = from s in _context.Cats
                               where s.Id == adopt.CatsId
                               select s;

                foreach (var s in adoptCat)
                {
                    s.Adopted = true;
                }

                _context.Add(adopt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            ViewData["CatsId"] = new SelectList(_context.Cats, "Id", "Name"); 
       
            return View(adopt);
        }

        // GET: Adopts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Adopt == null)
            {
                return NotFound();
            }

            var adopt = await _context.Adopt.FindAsync(id);
            if (adopt == null)
            {
                return NotFound();
            }

           
            //hämtar upp obokade katter
            var catContext = _context.Cats
                .Where(c => c.Adopted == false)
                .Select(c => c)
                .ToList();
            //plockar upp den katt som också är vald i denna adoptionsbokning
            var cat = _context.Cats
           .Where(c => c.Id == adopt.CatsId)
           .Select(c => c)
           .FirstOrDefault();

            //adderar till select-listan på edit
            if(cat != null)
            {
                catContext.Add(cat);
            }

            ViewData["CatsId"] = new SelectList(catContext, "Id", "Name", adopt.CatsId);
            return View(adopt);
        }

        // POST: Adopts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdoptId,AdoptName,Email,Number,Pickup,CatsId")] Adopt adopt)
        {
            if (id != adopt.AdoptId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adopt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdoptExists(adopt.AdoptId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatsId"] = new SelectList(_context.Cats, "Id", "Name", adopt.CatsId);
            return View(adopt);
        }

        // GET: Adopts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Adopt == null)
            {
                return NotFound();
            }

            var adopt = await _context.Adopt
                .Include(a => a.Cats)
                .FirstOrDefaultAsync(m => m.AdoptId == id);
            if (adopt == null)
            {
                return NotFound();
            }

            return View(adopt);
        }

        // POST: Adopts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Adopt == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Adopt'  is null.");
            }
            var adopt = await _context.Adopt.FindAsync(id);
            if (adopt != null)
            {
                _context.Adopt.Remove(adopt);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdoptExists(int id)
        {
          return (_context.Adopt?.Any(e => e.AdoptId == id)).GetValueOrDefault();
        }
    }
}

ProjektKatthem/Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjektKatthem.Data;
using ProjektKatthem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;

namespace ProjektKatthem.Controllers
{
    public class CatsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private string wwwRootPath;

        public CatsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            wwwRootPath = _hostEnvironment.WebRootPath;
        }

        // GET: Cats
        public async Task<IActionResult> Index()
        {
              return _context.Cats != null ? 
                          View(await _context.Cats.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Cats'  is null.");
        }

        // GET: Cats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cats == null)
            {
                return NotFound();
            }

            var cats = await _context.Cats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cats == null)
            {
                return NotFound();
            }

            return View(cats);
        }

        [Authorize]
        // GET: Cats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,Breed,ImgFile,Adopted,Registered,Info")] Cats cats)
        {
            if (ModelState.IsValid)
            {
                if (cats.ImgFile != null)
                {

                    //Spara bilder till wwwroot
                    string fileName = Path.GetFileNameWithoutExtension(cats.ImgFile.FileName);
                    string extension = Path.GetExtension(cats.ImgFile.FileName);

                    //Plockar bort mellanslag i filnam + lägger till timestamp
                    cats.ImgName = fileName = fileName.Replace(" ", String.Empty) + DateTime.Now.ToString("yymmssfff") + extension;

                    string path = Path.Combine(wwwRootPath + "/imagesupload", fileName);

                    //Lagra Fil
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await cats.ImgFile.CopyToAsync(fileStream);
                    }


                }
                else
                {
                    cats.ImgFile = null;
                }


                _context.Add(cats);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cats);
        }

        [Authorize]
        // GET: Cats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cats == null)
            {
                return NotFound();
            }

            var cats = await _context.Cats.FindAsync(id);
            if (cats == null)
            {
                return NotFound();
            }
            return View(cats);
        }
        [Authorize]
        // POST: Cats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Gender,Age,Breed,ImgName,Adopted,Registered,Info")] Cats cats)
        {
            if (id != cats.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)

            {
                try
                {
                    if (cats.ImgFile != null)
                {

                    //Spara bilder till wwwroot
                    string fileName = Path.GetFileNameWithoutExtension(cats.ImgFile.FileName);
                    string extension = Path.GetExtension(cats.ImgFile.FileName);

                    //Plockar bort mellanslag i filnam + lägger till timestamp
                    cats.ImgName = fileName = fileName.Replace(" ", String.Empty) + DateTime.Now.ToString("yymmssfff") + extension;

                    string path = Path.Combine(wwwRootPath + "/imagesupload", fileName);

                    //Lagra Fil
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await cats.ImgFile.CopyToAsync(fileStream);
                    }


                }
                else
                {
                    if(cats.ImgName != "") {
                        cats.ImgName = cats.ImgName;

                    } else {
                        cats.ImgFile = null;
                    }

                    
                }

                
                    _context.Update(cats);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CatsExists(cats.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cats);
        }
        [Authorize]
        // GET: Cats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cats == null)
            {
                return NotFound();
            }

            var cats = await _context.Cats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cats == null)
            {
                return NotFound();
            }

            return View(cats);
        }
        [Authorize]
        // POST: Cats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cats == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cats'  is null.");
            }
            var cats = await _context.Cats.Include(c => c.Adopt).FirstOrDefaultAsync(m => m.Id == id);
            if (cats != null)
            {
                _context.Cats.Remove(cats);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CatsExists(int id)
        {
          return (_context.Cats?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjektKatthem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gröndals Katthem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjektKatthem.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Cabin&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/grondallogo.png" style="width:200px" alt="Logotyp" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Startsida</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cats" asp-action="Index">Våra katter</a>
                        </li>
                  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Support">Stöd oss</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Kontakta oss</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Adopts" asp-action="Index">Adoption</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Registrera ny användare</a>
                            </li>
                        }

                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-dark">
        <div class="center">
            <img style="width: 25px" src="~/img/caticon.png" alt="Kattikon" />
            Gröndals Katthem - <a asp-area="" asp-controller="Home" asp-action="Contact">Kontakta oss</a> - <a asp-area="Identity" asp-page="/Account/Login">Personal</a><img style="width: 25px; margin-left: 5px;" src="~/img/caticon.png" alt="Kattikon" />
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>